### ISSUE TITLE
invalid token when trying to make an HTTP POST request for Firebase Cloud Messaging

### ISSUE THREAD

**Issue by Charles-Johnson** [durch/rust-goauth#11]
**Describe the bug**
Received HTTP 401 when using a JWT produced as in the README to make a POST request to send a firebase cloud message. Error message:
```rust
Response {
    url: "https://fcm.googleapis.com/v1/projects/my-project/messages:send", 
    status: 401, 
    headers: {
        "www-authenticate": "Bearer realm=\"https://accounts.google.com/\", error=\"invalid_token\"", 
        "vary": "X-Origin", 
        "vary": "Referer", 
        "vary": "Origin,Accept-Encoding", 
        "content-type": "application/json; charset=UTF-8", 
        "date": "Tue, 21 Jul 2020 09:10:21 GMT", 
        "server": "ESF", 
        "cache-control": "private", 
        "x-xss-protection": "0", 
        "x-frame-options": "SAMEORIGIN", 
        "x-content-type-options": "nosniff",
        "alt-svc": "h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-25=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
        "accept-ranges": "none", 
        "transfer-encoding": "chunked"
    } 
}
```

**To Reproduce**
I used the code in the README to prepare a `token`. I then used that `token` to make a POST request using `reqwest` like so
```rust
let client = Client::new();
let request = client
    .post("https://fcm.googleapis.com/v1/projects/my-project/messages:send")
    .bearer_auth(token)
    .json("{}")
    .build()?;
let response = client.execute(request).await?;
println!("{:?}", response);
```
I noticed that the service account I used differed from `dummy_credentials_file_for_tests.json` in the `token_uri` value. I had `https://oauth2.googleapis.com/token` whereas the dummy file had `https://accounts.google.com/o/oauth2/token`

**Environment**
 - Rust version: `1.43.1`
 - lib version `0.7.2`

**Comment by durch** [comment]
@Charles-Johnson you're passing in the token object itself, which then gets converted to `reqwest::HeaderValue`, in order to pass in the valid token you should use the `access_token()` method, so instead of `bearer_auth(token)`, use `bearer_auth(token.access.token())`. This should get you past the 401, but you'll likely hit a 400 as Firebase requires a specific message format.

I'll update the documentation to make it clearer how to use the token.

**Comment by Charles-Johnson** [comment]
Thanks! That solved the 401 problem. I intentionally left out the body and managed to solve the 400 error.

**Comment by durch** [comment]
Nice! Happy to help :D
