### ISSUE TITLE
Goauth client for get_token and co.

### ISSUE THREAD

**Issue by adelbertc** [durch/rust-goauth#12]
**Is your feature request related to a problem? Please describe.**
Currently it looks like token fetches [create a reqwest::Client](https://docs.rs/goauth/0.7.2/src/goauth/lib.rs.html#182-197) for each `get_token` call. In the context of my app which interacts with Google services, I already have a `reqwest::Client` I use for all the API calls I am making - it would be nice to also be able to re-use that `Client` for fetching the token.

**Describe the solution you'd like**
Perhaps we can have something like:

```rust
struct TokenFetcher {
  client: Client
}

impl TokenFetcher {
  async fn get_token(&self, jwt: &Jwt<JwtClaims>, credentials: &Credentials) -> Result<Token> { ... }
}
```

**Describe alternatives you've considered**
As far as I can tell the `get_token` variants all just spawn a `Client` internally with no opportunity to inject our own.

**Additional context**
I am happy to make a PR for this if such an addition would be welcome to the library.

As a meta-point I am also wondering if either this library or another library that integrates nicely with this library can handle token refreshes and the like? I can also see such functionality being part of the aforementioned `TokenFetcher` impl, e.g.

```rust
struct TokenFetcher {
  client: Client,
  token: Arc<RwLock<Token>>,
}

impl TokenFetcher {
  async fn get_token(&self, jwt: &Jwt<JwtClaims>, credentials: &Credentials) -> Result<Token> { ... }

  async fn refresh_token(&mut self, jwt: &Jwt<JwtClaims>, credentials: &Credentials) -> Result<()> {
    // check if token is still valid against some Google API
    // if not fetch a new token and swap out `self.token`
  }
}
```

**Comment by durch** [comment]
Hi @adelbertc thanks for the request! I'd be happy to take a PR, its a worthwhile feature for sure :)

**Comment by adelbertc** [comment]
Awesome, expect a PR in the next couple days!

**Comment by adelbertc** [comment]
@durch As promised: https://github.com/durch/rust-goauth/pull/13
