### ISSUE TITLE
Release plan for support on tokio v1.0?

### ISSUE THREAD

**Issue by fanatid** [durch/rust-goauth#16]
https://tokio.rs/blog/2020-10-tokio-0-3

**Comment by durch** [comment]
@fanatid thank you for raising the issue, will come back with a plan  :)

**Comment by durch** [comment]
Looks like all we need is hyper `0.14`, which should be coming soon -> https://github.com/hyperium/hyper/issues/2302

**Comment by jamtur01** [comment]
Hyper 0.14.x is released - looks like they've gone to tokio 1.0 there.

**Comment by durch** [comment]
Published as `0.9.0`
