### ISSUE TITLE
How to update 'exp' when using 'TokenFetcher'

### ISSUE THREAD

**Issue by njam** [durch/rust-goauth#17]
**Describe the bug**
I'm trying to use the `TokenFetcher`, but 2h after creating the first token I get this error:
```
TokenErr: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.
```

I think the problem is, that the initial `JwtClaim`'s `exp` value is static, and will not be updated when the token gets refreshed.

**To Reproduce**
Use the TokenFetcher to repeatedly fetch a token:
```rust
let credentials = Credentials::from_file("credentials.json")?;
let claims = JwtClaims::new(credentials.iss(), &Scope::CloudPlatform, "https://www.googleapis.com/oauth2/v4/token".into(), None, None);
let jwt = Jwt::new(claims, credentials.rsa_key()?, None);
let token_fetcher = TokenFetcher::new(jwt, credentials, time::Duration::new(1, 0));
loop {
    let token = token_fetcher.fetch_token().await?;
    println!("Token: {:?}", token);
    std::thread::sleep(Duration::from_secs(60));
}
```

Wait 2h until you get the error.

**Expected behavior**
I guess the claim's expiration should be updated as time passes.

Maybe I'm using the API wrongly, or maybe this should be a feature request instead of a bug. Happy for your feedback.

**Environment**
 - Rust version: 1.51.0-nightly
 - lib version 0.9.0

**Comment by durch** [comment]
@njam thank you for raising this, its been a while since I've looked at that code, will get up to speed, my guess is your hunch is correct, will keep you posted.

**Comment by durch** [comment]
@njam could you please test `0.10.0-beta0` it should solve the issue, the only snag is that `TokenFetcher` needs to be mutable now.

**Comment by durch** [comment]
`0.10.0-beta1` published for crates.io, thank you for #19

**Comment by njam** [comment]
I can confirm that `0.10.0-beta1` solves the problem, thanks for the quick fix!
