### ISSUE TITLE
There are some missing scopes

### ISSUE THREAD

**Issue by TheBestJohn** [durch/rust-goauth#2]
Trying this out for FCM and it needs `https://www.googleapis.com/auth/firebase.messaging` as a scope. Is there a way to add this locally or does it need to be added to the scopes file. If the latter, perhaps an option to add a generic url to the scopes list?

**Comment by TheBestJohn** [comment]
Also, the oauth spec says you should be able to send a list of scopes for the token

**Comment by durch** [comment]
@TheBestJohn totally missed this, I'll look into the scopes, the generic route definitely feels like a way to go.

**Comment by TheBestJohn** [comment]
cool. I'll see about looking into any changes you make if you'd like. It's been a while since I was playing with this :)

**Comment by durch** [comment]
Added in 0.4.1
