### ISSUE TITLE
Make use of async client

### ISSUE THREAD

**Issue by daniel-abramov** [durch/rust-goauth#3]
I think it would be nice to return `Future<Item = Token, Error = ...>` instead of a plain `Result`. The one can execute a future in a blocking way and get the result, but the one can't simply run the blocking operating as future. Also it's most likely that the crate will be used on a server side where tokio definitely makes sense.

**Comment by durch** [comment]
@application-developer-DA great suggestion, I'm happy to see this used in the wild. I took a stab at the implementation, not clean, and not tested in a real world scenario, I'd appreciate any feedback you might have. Version `0.6.0-beta` pushed to crates.io.

**Comment by daniel-abramov** [comment]
Ok, I've just left some feedback to the commit.
