### ISSUE TITLE
Update to reqwest 0.10

### ISSUE THREAD

**Issue by MOZGIII** [durch/rust-goauth#8]
`reqwest` 0.10 has switched to `std::future::Future`,  `hyper` 0.13 and `tokio` 0.2!

We're upgrading the dependencies, and we noticed this crate is still using `reqwest` 0.9. Any plans on upgrading to `reqwest` `0.10`+?

**Comment by durch** [comment]
@MOZGIII Thanks for raising this, yeah, there will be an update geared towards moving to `futures 0.3` in the next two weeks.

**Comment by durch** [comment]
Turned out to be much less of a hassle, version `0.7.0` pushed to crates.io. In addition to dependency updates API is now async first, and functions have nicer names, `get_token` and `get_token_blocking`.
